"""Assemble the Ada-Efeso ground layer from PixelLab terrain tiles only.

The script deliberately never draws, resizes, recolors, or labels pixels. Every
32x32 cell in the resulting PNG is an exact paste of one of the sixteen source
tiles generated by the PixelLab MCP. Buildings, vehicles, furniture, trees,
fences, and other raised objects belong to the runtime sprite layer in map.js.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image, ImageChops


ROOT = Path(__file__).resolve().parents[1]
TERRAIN_DIR = ROOT / "assets" / "generated" / "ada-efeso-pixellab" / "terrain-borderless"
OUTPUT = ROOT / "maps" / "ada-efeso" / "base-pixellab-borderless.png"

TILE_SIZE = 32
COLS = 72
ROWS = 96

# PixelLab create_tiles_pro output order.
GRASS = 0
ASPHALT = 1
SIDEWALK = 2
PLAZA = 3
COURTYARD = 4
PLAYGROUND = 5
PARKING_BAY = 6
LANE_DASH = 7
DOUBLE_YELLOW = 8
ZEBRA = 9
CURB = 10
PLAZA_BORDER = 11
MEDIAN = 12
MEDIAN_LEFT = 13
MEDIAN_RIGHT = 14
HEDGE = 15


def load_tiles() -> list[Image.Image]:
    tiles: list[Image.Image] = []
    for index in range(16):
        path = TERRAIN_DIR / f"tile-{index:02d}.png"
        tile = Image.open(path).convert("RGBA")
        if tile.size != (TILE_SIZE, TILE_SIZE):
            raise ValueError(f"{path} must be {TILE_SIZE}x{TILE_SIZE}, got {tile.size}")
        tiles.append(tile)
    return tiles


def build_layout() -> list[list[int]]:
    cells = [[GRASS for _ in range(COLS)] for _ in range(ROWS)]

    def rect(left: int, top: int, right: int, bottom: int, tile: int) -> None:
        if not (0 <= left <= right <= COLS and 0 <= top <= bottom <= ROWS):
            raise ValueError(f"rectangle outside map: {(left, top, right, bottom)}")
        for row in range(top, bottom):
            cells[row][left:right] = [tile] * (right - left)

    def plaza_triplet(top: int) -> None:
        # Concrete aprons under the two rows of transparent building sprites.
        rect(14, top - 7, 47, top, SIDEWALK)
        rect(14, top + 8, 47, top + 13, SIDEWALK)

        # Three genuinely square plazas, linked by narrower paved passages.
        for left in (14, 25, 36):
            rect(left, top, left + 8, top + 8, PLAZA)
        rect(22, top + 3, 25, top + 5, PLAZA)
        rect(33, top + 3, 36, top + 5, PLAZA)
        rect(44, top + 3, 52, top + 5, PLAZA)

        # Pedestrian access from Avenida Ada.
        rect(10, top + 3, 14, top + 5, SIDEWALK)

    def parking(left: int, top: int, right: int, bottom: int) -> None:
        rect(left, top, right, bottom, ASPHALT)
        center = top + (bottom - top) // 2

        # PixelLab parking-bay line tiles; no cars are baked into this layer.
        for col in range(left + 1, right - 1, 3):
            rect(col, top + 1, col + 1, center, PARKING_BAY)
            rect(col, center + 1, col + 1, bottom - 1, PARKING_BAY)

        if right - left >= 3:
            rect(left + 1, center, right - 1, center + 1, MEDIAN)
            rect(left, center, left + 1, center + 1, MEDIAN_LEFT)
            rect(right - 1, center, right, center + 1, MEDIAN_RIGHT)

    # Avenida Ada: four lanes, two per direction, with sidewalks.
    rect(1, 0, 2, ROWS, SIDEWALK)
    rect(2, 0, 10, ROWS, ASPHALT)
    rect(10, 0, 13, ROWS, SIDEWALK)
    rect(3, 0, 4, ROWS, LANE_DASH)
    rect(5, 0, 6, ROWS, DOUBLE_YELLOW)
    rect(8, 0, 9, ROWS, LANE_DASH)

    # Three pedestrian streets and the continuous Paseo Efeso.
    plaza_triplet(9)
    plaza_triplet(40)
    plaza_triplet(70)
    rect(47, 2, 52, 84, PLAZA)

    # Safe zebra crossings on Ada, aligned with the three plaza streets.
    for top in (12, 43, 73):
        rect(2, top, 10, top + 2, ZEBRA)

    # Alternating parking bands with planted medians.
    parking(15, 24, 42, 34)
    parking(15, 54, 42, 64)

    # Fenced university campus ground and its separate parking area.
    rect(53, 4, 70, 52, COURTYARD)
    rect(55, 15, 68, 29, SIDEWALK)
    rect(55, 35, 68, 49, SIDEWALK)
    parking(53, 56, 70, 68)

    # Southern service band: parking, playground, parking.
    parking(14, 86, 35, 95)
    rect(36, 86, 44, 95, PLAYGROUND)
    parking(45, 86, 70, 95)

    # PixelLab hedge edge closes the residential side without adding objects.
    rect(13, 0, 14, ROWS, HEDGE)
    rect(71, 0, 72, ROWS, HEDGE)
    return cells


def render(cells: list[list[int]], tiles: list[Image.Image]) -> Image.Image:
    canvas = Image.new("RGBA", (COLS * TILE_SIZE, ROWS * TILE_SIZE))
    for row, line in enumerate(cells):
        for col, tile_index in enumerate(line):
            canvas.paste(tiles[tile_index], (col * TILE_SIZE, row * TILE_SIZE))
    return canvas


def verify_exact_cells(image: Image.Image, cells: list[list[int]], tiles: list[Image.Image]) -> None:
    if image.size != (COLS * TILE_SIZE, ROWS * TILE_SIZE):
        raise ValueError(f"wrong output size: {image.size}")
    rgba = image.convert("RGBA")
    for row, line in enumerate(cells):
        for col, tile_index in enumerate(line):
            box = (
                col * TILE_SIZE,
                row * TILE_SIZE,
                (col + 1) * TILE_SIZE,
                (row + 1) * TILE_SIZE,
            )
            if ImageChops.difference(rgba.crop(box), tiles[tile_index]).getbbox() is not None:
                raise ValueError(f"cell ({col}, {row}) is not an exact PixelLab tile")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="verify the existing PNG without rewriting it")
    args = parser.parse_args()

    tiles = load_tiles()
    cells = build_layout()
    expected = render(cells, tiles)

    if args.check:
        actual = Image.open(OUTPUT)
        verify_exact_cells(actual, cells, tiles)
        if ImageChops.difference(actual.convert("RGBA"), expected).getbbox() is not None:
            raise ValueError("base-pixellab-borderless.png does not match the declared layout")
        print(f"OK: {OUTPUT} contains only exact PixelLab terrain tiles")
        return

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    expected.save(OUTPUT, optimize=True)
    verify_exact_cells(Image.open(OUTPUT), cells, tiles)
    print(f"Wrote {OUTPUT} ({COLS}x{ROWS} tiles, {expected.width}x{expected.height}px)")


if __name__ == "__main__":
    main()
